"""file column filename

Revision ID: 689fef052fe7
Revises: d1bdf2ac6458
Create Date: 2025-10-03 06:54:44.439331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689fef052fe7'
down_revision = 'd1bdf2ac6458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###
